name: Test Build

on:
  push:
    branches: [ testing ]
  workflow_dispatch:
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: task-connector-action
        uses: Green-Hub-Tools/task-connector@0.0.2
